### ISSUE TITLE
Unable to combine draggable with scrollable on mobile

### ISSUE THREAD

**Issue by Andrioden** [PuruVJ/neodrag#147]
**Problem**
I have an `box` that is draggable with a `header`+`content` part. I want the `header` part to be the drag-handle, and the `content` scrollable. However, since neodrag sets `touch-action: none` on the whole box, scrolling no longer work.

![image](https://github.com/PuruVJ/neodrag/assets/393376/558c4c5a-63d0-4cd7-8a08-1a37d6a12eec)

**Solution / Workaround css**
``` css

.box{
    touch-action: auto !important;
}

.box .header {
    touch-action: none;
}

.box .content {
    overflow-y: auto;
}
```
